using Godot;
using System;

public partial class SecretPassage : Door
{
	public float Suspicion; //Suspicion generated by using the secret passage
	
	// Called when the node enters the scene tree for the first time.
	public override void _Ready()
	{
	}

	// Called every frame. 'delta' is the elapsed time since the previous frame.
	public override void _Process(double delta)
	{
	}
	
	//Add to suspicion when used
	public void AddSuspicion()
	{
		
	}
}
