using Godot;
using System;

public partial class SecretPassage : Interactable
{
	public float Suspicion; //Suspicion generated by using the secret passage
	
	[Export]
	public int ConnectedRoom;
	
	// Called when the node enters the scene tree for the first time.
	public override void _Ready()
	{
		base._Ready();
		Suspicion = 7;
	}

	// Called every frame. 'delta' is the elapsed time since the previous frame.
	public override void _Process(double delta)
	{
	}
	
	//Begin dialogue
	public override void BeginDialogue()
	{
		base.BeginDialogue();
		//Set second to last dialogue option to take the player to the next room
		GridContainer DialogueContainer = ((GridContainer)DialogueBox.GetNode("MainUI/Dialogue/Dialog"));
		int DialogueCount = DialogueContainer.GetChildCount();
		DialogueOption PickUpOption = (DialogueOption)DialogueContainer.GetChild(DialogueCount-2);
		PickUpOption.Pressed += AddSuspicion;
	}
	
	//Add to suspicion when used
	public void AddSuspicion()
	{
		Game.Instance.IncreaseLocalSuspicion(RoomId,Suspicion);
		Game.Instance.IncreaseLocalSuspicion(ConnectedRoom,Suspicion);
		//Mark the room as having saved data
		Game.Instance.FirstSaved[RoomId] = true;
		//Change the music based on the room
		if(ConnectedRoom == 20 || ConnectedRoom == 5 || ConnectedRoom == 13)
		{ //If the player is going to the boss room or the bar
			((MusicPlayer)GetTree().GetRoot().GetChild(1)).ChangeSong(ConnectedRoom);
		}
		else if(RoomId == 20 || RoomId == 5 || RoomId == 13)
		{ //If the player is leaving the boss room or the bar
			((MusicPlayer)GetTree().GetRoot().GetChild(1)).ChangeSong(ConnectedRoom);
		}
		//Change scene based on the room the passage takes the player during the next physics process
		CallDeferred(nameof(PhysicsProcessSceneChange));
	}
	
	//Change scenes during the next physics process
	public void PhysicsProcessSceneChange()
	{
		if(!IsInsideTree())
		{
			return;
		}
		GetTree().ChangeSceneToFile(Game.Instance.roomIDS[ConnectedRoom]);
	}
}
